name: Deploy Backend to Somee

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cài .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Restore
      - name: Restore dependencies
        run: dotnet restore BackendApi/BackendApi.csproj

      # 4. Build
      - name: Build
        run: dotnet build BackendApi/BackendApi.csproj -c Release --no-restore

      # 5. Publish
      - name: Publish
        run: dotnet publish BackendApi/BackendApi.csproj -c Release -o publish

      # 6. Deploy FTP lên Somee
      - name: Deploy to Somee via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: publish/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
